version: '2.1'
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    - SERVERURL=auto
    - SERVERPORT=51820
    - PEERS=22
    - PEERDNS=auto
    - INTERNAL_SUBNET=172.16.0.0
    - ALLOWEDIPS=169.254.0.0/16
    - PERSISTENT_KEEPALIVE=5
    volumes:
    - ./config:/config
    - /lib/modules:/lib/modules
    ports:
    - 51820:51820/udp
    sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
    restart: always
networks:
  default:
    name: docker-vpn
    external: true
